# Generated by Django 4.2.4 on 2023-09-04 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование категории')),
                ('description', models.CharField(max_length=100, verbose_name='описания')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'наименование категории',
                'verbose_name_plural': 'наименование категорий',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название товара')),
                ('description', models.TextField(verbose_name='описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='превью')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена за покупку')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='дата добавления')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homework.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'название товара',
                'verbose_name_plural': 'название товаров',
            },
        ),
    ]
