# Generated by Django 4.2.4 on 2023-09-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование продукта')),
                ('description', models.TextField(verbose_name='описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='превью')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена за покупку')),
            ],
            options={
                'verbose_name': 'наименование продукта',
                'verbose_name_plural': 'наименование продуктов',
            },
        ),
    ]
