# Generated by Django 4.2.5 on 2023-09-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog_previews/', verbose_name='Превью'),
        ),
    ]
