# Generated by Django 4.2.5 on 2023-09-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_alter_blogpost_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
